## Minimal local-only mise tasks
## - 目的: ローカル開発で使う dev/lint/fmt のみ
## - 依存: Go と Node をmiseで固定（余計な依存は追加しない）

[tools]
go = "1.25"
node = "20"

# 開発サーバー（バックエンド:8888 + フロント:5173）
[tasks.dev]
description = "開発サーバー起動 (backend:8888 + frontend:5173)"
dir = "."
run = "scripts/dev.sh"
raw = true

# Lint（Go: vet、Frontend: ESLint）
[tasks.lint]
description = "軽量Lint: go vet + Prettier check"
dir = "."
run = '''
bash -lc 'set -e
  (cd backend && go vet ./...)
  (cd frontend && npx -y prettier@3 --check "**/*.{ts,tsx,css,html}")
'
'''

# Format（Go: go fmt、Frontend: Prettier書き込み）
# NOTE: プロジェクトにPrettierは依存追加しない方針のため npx で取得
[tasks.fmt]
description = "go fmt + prettier --write"
dir = "."
run = '''
bash -lc 'set -e
  (cd backend && go fmt ./...)
  (cd frontend && npx -y prettier@3 --write "**/*.{ts,tsx,css,html}")
'
'''
